name: 'Request a New Feature'
description: 'Use this template to propose a new feature'
title: '[FEATURE]: <a short description of my proposal>'
labels:
  - 'enhancement'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain what your proposed feature would do and why this is useful.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Any additional info you'd like to provide.